export const UPDATE_SORTING = 'UPDATE_SORTING';
export const UPDATE_TRANSFERS = 'UPDATE_TRANSFERS';
export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';
export const ERROR_DISPLAY_ON = 'ERROR_DISPLAY_ON';
export const ERROR_DISPLAY_OFF = 'ERROR_DISPLAY_OFF';
export const SHOW_MORE_TICKETS = 'SHOW_MORE_TICKETS';